#!/bin/bash

for i in {1..9}; do
  gsettings set org.gnome.shell.keybindings switch-to-application-$i "[]"
  gsettings set org.gnome.shell.extensions.dash-to-dock app-hotkey-$i "[]"
  # I'm ignoring this for now since technically Material-Shell already implement these keybindings
  #gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-$i "['<Super>$i']"
  #gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-$i "['<Super><Shift>$i']"
done
gsettings set org.gnome.shell.extensions.dash-to-dock app-hotkey-10 "[]"
