# Set variables that will be also available on GUI
source $HOME/.passwords.sh
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/home/bamorim/bin:/home/bamorim/bin/scripts:$PATH
PATH="/usr/local/heroku/bin:$PATH"
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
PATH=$HOME/.elmenv/bin:$PATH
export PATH
export ELM_HOME=/usr/lib/node_modules/elm/share

eval "$(direnv hook zsh)"
eval "$(elmenv init -)"
eval $(keychain --eval --quiet)

[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx
