BINDIR=$HOME/bin

export E=/Volumes/Extension
export EHOME=$E$HOME

PATH=$HOME/.local/bin:$PATH
PATH=$BINDIR:$BINDIR/scripts:$PATH
PATH=/usr/local/heroku/bin:$PATH
PATH=$HOME/.cargo/bin:$PATH
PATH=$HOME/.dotnet/tools:$PATH
export GOPATH=~/go
PATH=$GOPATH/bin:$PATH
export PATH
