ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"
DEFAULT_USER=`whoami`
COMPLETION_WAITING_DOTS="true"
plugins=(z dotenv)

. $ZSH/oh-my-zsh.sh
. $HOME/.aliases
. $HOME/.iterm2_shell_integration.zsh
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash
eval $(thefuck --alias)
source <(plz --completion_script)
export EDITOR='mvim -v'
export LC_ALL=en_US.UTF-8
