#!/bin/sh

MAIN_MONITOR=eDP1
BIGGER_MONITOR=HDMI1

case $1 in
  on)
    echo "Turning on cinema mode..."
    xrandr --output $BIGGER_MONITOR --auto --right-of $MAIN_MONITOR
    xrandr --output $MAIN_MONITOR --mode 1368x768
    ~/.fehbg
    ;;
  off)
    echo "Turning off cinema mode..."
    xrandr --output $BIGGER_MONITOR --off
    xrandr --output $MAIN_MONITOR --mode 1920x1080
    ~/.fehbg
    ;;
  *)
    echo "Usage: $(basename "$0") on|off"
    ;;
esac
